"""add database constraints

Revision ID: bf23c0b79af2
Revises: a97446dc27af
Create Date: 2026-08-30 05:59:55.659811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf23c0b79af2'
down_revision: Union[str, Sequence[str], None] = 'a97446dc27af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_account_name_not_empty', 'accounts', "account_name != ''")
    op.create_check_constraint('ck_opening_balance_non_negative', 'accounts', 'opening_balance >= 0')
    op.create_check_constraint('ck_valid_account_type', 'accounts', "account_type IN ('checking', 'savings', 'credit_card', 'cash', 'investment', 'loan')")
    op.create_check_constraint('ck_valid_currency', 'accounts', "currency IN ('USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD')")
    op.create_check_constraint('ck_category_name_not_empty', 'categories', "category_name != ''")
    op.create_check_constraint('ck_parent_category_not_self', 'categories', 'parent_category_id IS NULL OR parent_category_id != category_id')
    op.create_check_constraint('ck_amount_positive', 'transactions', 'amount > 0')
    op.create_check_constraint('ck_valid_payment_method', 'transactions', "payment_method IN ('card', 'upi', 'cash', 'bank_transfer', 'wallet')")
    op.create_check_constraint('ck_valid_transaction_kind', 'transactions', "transaction_kind IN ('income', 'expense', 'transfer')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_valid_transaction_kind', 'transactions', type_='check')
    op.drop_constraint('ck_valid_payment_method', 'transactions', type_='check')
    op.drop_constraint('ck_amount_positive', 'transactions', type_='check')
    op.drop_constraint('ck_parent_category_not_self', 'categories', type_='check')
    op.drop_constraint('ck_category_name_not_empty', 'categories', type_='check')
    op.drop_constraint('ck_valid_currency', 'accounts', type_='check')
    op.drop_constraint('ck_valid_account_type', 'accounts', type_='check')
    op.drop_constraint('ck_opening_balance_non_negative', 'accounts', type_='check')
    op.drop_constraint('ck_account_name_not_empty', 'accounts', type_='check')
    # ### end Alembic commands ###
